Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EndOfLine:
  Enabled: false

Style/MethodName:
  Enabled: false

Style/VariableName:
  Enabled: false

Metrics:
  Enabled: false
