apiId: [apiId] #apiId for the datasources. found in the datasources section in the netuitive ui
baseAddr: "api.uat.netuitive.com" #where to send the data. in most cases use the default
port: nil #in most cases this will be nil
elementName: [elementName] #name of the element to assign metrics to in netuitive. if unsure, just use the name of your app
debugLevel: "debug" #options (in ascending order of debugness) are: error, info, debug
netuitivedAddr: "localhost"
netuitivedPort: 8875
interval: 60